#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleMidias.BancoDeDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BancoControleMidia")]
	public partial class LinqControleMidiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAmigo(Amigo instance);
    partial void UpdateAmigo(Amigo instance);
    partial void DeleteAmigo(Amigo instance);
    partial void InsertMidia(Midia instance);
    partial void UpdateMidia(Midia instance);
    partial void DeleteMidia(Midia instance);
    #endregion
		
		public LinqControleMidiaDataContext() : 
				base(global::ControleMidias.Properties.Settings.Default.BancoControleMidiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqControleMidiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqControleMidiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqControleMidiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqControleMidiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Amigo> Amigos
		{
			get
			{
				return this.GetTable<Amigo>();
			}
		}
		
		public System.Data.Linq.Table<Midia> Midias
		{
			get
			{
				return this.GetTable<Midia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Amigo")]
	public partial class Amigo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAmigo;
		
		private string _Nome;
		
		private string _Apelido;
		
		private string _Celular;
		
		private string _Telefone;
		
		private string _Email;
		
		private string _Cidade;
		
		private string _Bairro;
		
		private string _NumeroCasa;
		
		private string _NomePai;
		
		private string _NomeMae;
		
		private EntitySet<Midia> _Midias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAmigoChanging(int value);
    partial void OnIdAmigoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnApelidoChanging(string value);
    partial void OnApelidoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnNumeroCasaChanging(string value);
    partial void OnNumeroCasaChanged();
    partial void OnNomePaiChanging(string value);
    partial void OnNomePaiChanged();
    partial void OnNomeMaeChanging(string value);
    partial void OnNomeMaeChanged();
    #endregion
		
		public Amigo()
		{
			this._Midias = new EntitySet<Midia>(new Action<Midia>(this.attach_Midias), new Action<Midia>(this.detach_Midias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAmigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAmigo
		{
			get
			{
				return this._IdAmigo;
			}
			set
			{
				if ((this._IdAmigo != value))
				{
					this.OnIdAmigoChanging(value);
					this.SendPropertyChanging();
					this._IdAmigo = value;
					this.SendPropertyChanged("IdAmigo");
					this.OnIdAmigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apelido", DbType="VarChar(50)")]
		public string Apelido
		{
			get
			{
				return this._Apelido;
			}
			set
			{
				if ((this._Apelido != value))
				{
					this.OnApelidoChanging(value);
					this.SendPropertyChanging();
					this._Apelido = value;
					this.SendPropertyChanged("Apelido");
					this.OnApelidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCasa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NumeroCasa
		{
			get
			{
				return this._NumeroCasa;
			}
			set
			{
				if ((this._NumeroCasa != value))
				{
					this.OnNumeroCasaChanging(value);
					this.SendPropertyChanging();
					this._NumeroCasa = value;
					this.SendPropertyChanged("NumeroCasa");
					this.OnNumeroCasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePai", DbType="VarChar(50)")]
		public string NomePai
		{
			get
			{
				return this._NomePai;
			}
			set
			{
				if ((this._NomePai != value))
				{
					this.OnNomePaiChanging(value);
					this.SendPropertyChanging();
					this._NomePai = value;
					this.SendPropertyChanged("NomePai");
					this.OnNomePaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeMae", DbType="VarChar(50)")]
		public string NomeMae
		{
			get
			{
				return this._NomeMae;
			}
			set
			{
				if ((this._NomeMae != value))
				{
					this.OnNomeMaeChanging(value);
					this.SendPropertyChanging();
					this._NomeMae = value;
					this.SendPropertyChanged("NomeMae");
					this.OnNomeMaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Amigo_Midia", Storage="_Midias", ThisKey="IdAmigo", OtherKey="IdAmigo")]
		public EntitySet<Midia> Midias
		{
			get
			{
				return this._Midias;
			}
			set
			{
				this._Midias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Midias(Midia entity)
		{
			this.SendPropertyChanging();
			entity.Amigo = this;
		}
		
		private void detach_Midias(Midia entity)
		{
			this.SendPropertyChanging();
			entity.Amigo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Midia")]
	public partial class Midia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMidia;
		
		private string _Nome;
		
		private string _Tipo;
		
		private System.Nullable<int> _IdAmigo;
		
		private System.Nullable<System.DateTime> _DataSaida;
		
		private System.Nullable<System.DateTime> _DataPrevistaEntrega;
		
		private System.Nullable<System.DateTime> _DataEfetivaEntrega;
		
		private EntityRef<Amigo> _Amigo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMidiaChanging(int value);
    partial void OnIdMidiaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnIdAmigoChanging(System.Nullable<int> value);
    partial void OnIdAmigoChanged();
    partial void OnDataSaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataSaidaChanged();
    partial void OnDataPrevistaEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPrevistaEntregaChanged();
    partial void OnDataEfetivaEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataEfetivaEntregaChanged();
    #endregion
		
		public Midia()
		{
			this._Amigo = default(EntityRef<Amigo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMidia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMidia
		{
			get
			{
				return this._IdMidia;
			}
			set
			{
				if ((this._IdMidia != value))
				{
					this.OnIdMidiaChanging(value);
					this.SendPropertyChanging();
					this._IdMidia = value;
					this.SendPropertyChanged("IdMidia");
					this.OnIdMidiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAmigo", DbType="Int")]
		public System.Nullable<int> IdAmigo
		{
			get
			{
				return this._IdAmigo;
			}
			set
			{
				if ((this._IdAmigo != value))
				{
					if (this._Amigo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAmigoChanging(value);
					this.SendPropertyChanging();
					this._IdAmigo = value;
					this.SendPropertyChanged("IdAmigo");
					this.OnIdAmigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSaida", DbType="Date")]
		public System.Nullable<System.DateTime> DataSaida
		{
			get
			{
				return this._DataSaida;
			}
			set
			{
				if ((this._DataSaida != value))
				{
					this.OnDataSaidaChanging(value);
					this.SendPropertyChanging();
					this._DataSaida = value;
					this.SendPropertyChanged("DataSaida");
					this.OnDataSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPrevistaEntrega", DbType="Date")]
		public System.Nullable<System.DateTime> DataPrevistaEntrega
		{
			get
			{
				return this._DataPrevistaEntrega;
			}
			set
			{
				if ((this._DataPrevistaEntrega != value))
				{
					this.OnDataPrevistaEntregaChanging(value);
					this.SendPropertyChanging();
					this._DataPrevistaEntrega = value;
					this.SendPropertyChanged("DataPrevistaEntrega");
					this.OnDataPrevistaEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEfetivaEntrega", DbType="Date")]
		public System.Nullable<System.DateTime> DataEfetivaEntrega
		{
			get
			{
				return this._DataEfetivaEntrega;
			}
			set
			{
				if ((this._DataEfetivaEntrega != value))
				{
					this.OnDataEfetivaEntregaChanging(value);
					this.SendPropertyChanging();
					this._DataEfetivaEntrega = value;
					this.SendPropertyChanged("DataEfetivaEntrega");
					this.OnDataEfetivaEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Amigo_Midia", Storage="_Amigo", ThisKey="IdAmigo", OtherKey="IdAmigo", IsForeignKey=true)]
		public Amigo Amigo
		{
			get
			{
				return this._Amigo.Entity;
			}
			set
			{
				Amigo previousValue = this._Amigo.Entity;
				if (((previousValue != value) 
							|| (this._Amigo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Amigo.Entity = null;
						previousValue.Midias.Remove(this);
					}
					this._Amigo.Entity = value;
					if ((value != null))
					{
						value.Midias.Add(this);
						this._IdAmigo = value.IdAmigo;
					}
					else
					{
						this._IdAmigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Amigo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
